### PR TITLE
Add 2nd Game - Android War!

### PR DESCRIPTION
**Pull request by Jabont**
### Description
Please describe what you do in this pull request...

### Do you want to get an early bird ticket for Hacktoberfest BKK? (For a person who can attend the event)
- [x] Yes (If you select yes, please type your email below)
- [ ] No

Your Email Address: (Optional) Jabont@hotmail.com

Note: if your project is not finish yet and don't want our mod to merge it. Simply add [WIP] next to pull request name. This make us recognize that your work is not done.

### CODE REVIEW

**Comment by Ryan-Willpower** [comment]
Two games but only 1 ticket na.

**Comment by Ryan-Willpower** [comment]
May I ask you which game do you want to send to the contest?

**Comment by Jabont** [comment]
Ohhh. sorry haha.
If I can send only 1 game I wanna choose this game (Android War).

**Comment by Ryan-Willpower** [comment]
Ok!!! Thanks for contributing with us again!! 💖

**Pull request merged**
